version: '3.7'
services:
  
  trino:
      image: 'trinodb/trino:latest'
      hostname: trino
      ports:
        - '8080:8080' 
      volumes:
        - ./trino:/etc/trino
      networks:
        - trino-network

  de_mysql:
      image: 'mysql:latest'
      container_name: de_mysql
      hostname: mysql
      ports:
        - '3308:3306'
      volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql:/etc/mysql/conf.d
      env_file:
        - .env
      networks:
        - trino-network

  hive-metastore:
      hostname: hive-metastore
      image: 'bitsondatadev/hive-metastore:latest'
      ports:
        - '9083:9083' # Metastore Thrift
      volumes:
        - ./hive-metastore/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
      environment:
        METASTORE_DB_HOSTNAME: de_mysql
      depends_on:
        - de_mysql
      networks:
        - trino-network

  minio:
      image: 'minio/minio:latest'
      hostname: minio
      container_name: minio
      ports:
        - '9000:9000'
        - '9001:9001'
      volumes:
        - ./minio:/data
      env_file:
        - .env
      command: server --console-address ":9001" /data
      networks:
        - trino-network

networks:
  trino-network:
    driver: bridge
