version: 2

sources: 
  - name: bronze
    tables:
        - name: raw_appearances
          external:
            location: 's3a://warehouse/bronze/raw_appearances'
          columns:
            - name: appearance_id
              data_type: string
            - name: game_id
              data_type: int
            - name: player_id
              data_type: int
            - name: player_club_id
              data_type: int
            - name: player_current_club_id
              data_type: int
            - name: date
              data_type: date
            - name: player_name
              data_type: string
            - name: competition_id
              data_type: string
            - name: yellow_cards
              data_type: int
            - name: red_cards
              data_type: int
            - name: goals
              data_type: int
            - name: assists
              data_type: int
            - name: minutes_played
              data_type: int

        - name: raw_games
          external:
            location: 's3a://warehouse/bronze/raw_games'
          columns:
            - name: game_id
              data_type: int
            - name: competition_id
              data_type: string
            - name: season
              data_type: int
            - name: round
              data_type: string
            - name: date
              data_type: int
            - name: home_club_id
              data_type: int
            - name: away_club_id
              data_type: int
            - name: home_club_goals
              data_type: int
            - name: away_club_goals
              data_type: int
            - name: home_club_position
              data_type: int
            - name: away_club_position
              data_type: int
            - name: home_club_manager_name
              data_type: string
            - name: away_club_manager_name
              data_type: string
            - name: stadium
              data_type: string
            - name: attendance
              data_type: int
            - name: referee
              data_type: string
            - name: url
              data_type: string
            - name: home_club_formation
              data_type: string
            - name: away_club_formation
              data_type: string
            - name: home_club_name
              data_type: string
            - name: away_club_name
              data_type: string
            - name: aggregate
              data_type: string
            - name: competition_type
              data_type: string

        - name: raw_game_events
          external:
            location: 's3a://warehouse/bronze/raw_game_events'
          columns:
            - name: game_event_id
              data_type: string
            - name: date
              data_type: date
            - name: game_id
              data_type: int
            - name: minute
              data_type: int
            - name: type
              data_type: string
            - name: club_id
              data_type: int
            - name: player_id
              data_type: int
            - name: description
              data_type: string
            - name: player_in_id
              data_type: double
            - name: player_assist_id
              data_type: double

        - name: raw_player_valuations
          external:
            location: 's3a://warehouse/bronze/raw_player_valuations'
          columns:
            - name: player_id
              data_type: int
            - name: date
              data_type: date
            - name: market_value_in_eur
              data_type: int
            - name: current_club_id
              data_type: int
            - name: player_club_domestic_competition_id
              data_type: string

        - name: raw_players
          external:
            location: 's3a://warehouse/bronze/raw_players'
          columns:
            - name: player_id
              data_type: int
            - name: first_name
              data_type: string
            - name: last_name
              data_type: string
            - name: name
              data_type: string
            - name: last_season
              data_type: int
            - name: current_club_id
              data_type: int
            - name: player_code
              data_type: string
            - name: country_of_birth
              data_type: string
            - name: city_of_birth
              data_type: string
            - name: country_of_citizenship
              data_type: string
            - name: date_of_birth
              data_type: string
            - name: sub_position
              data_type: string
            - name: position
              data_type: string
            - name: foot
              data_type: string
            - name: height_in_cm
              data_type: double
            - name: contract_expiration_date
              data_type: date
            - name: agent_name
              data_type: string
            - name: image_url
              data_type: string
            - name: url
              data_type: string
            - name: current_club_domestic_competition_id
              data_type: string
            - name: current_club_name
              data_type: string
            - name: market_value_in_eur
              data_type: int
            - name: highest_market_value_in_eur
              data_type: int

        - name: raw_club_games
          external:
            location: 's3a://warehouse/bronze/raw_club_games'
          columns:
            - name: game_id
              data_type: int
            - name: club_id
              data_type: int
            - name: own_goals
              data_type: int
            - name: own_position
              data_type: double
            - name: own_manager_name
              data_type: string
            - name: opponent_id
              data_type: int
            - name: opponent_goals
              data_type: int
            - name: opponent_position
              data_type: double
            - name: opponent_manager_name
              data_type: string
            - name: hosting
              data_type: string
            - name: is_win
              data_type: int

        - name: raw_clubs
          external:
            location: 's3a://warehouse/bronze/raw_clubs'
          columns:
            - name: club_id
              data_type: int
            - name: club_code
              data_type: string
            - name: name
              data_type: string
            - name: domestic_competition_id
              data_type: string
            - name: total_market_value
              data_type: double
            - name: squad_size
              data_type: int
            - name: average_age
              data_type: decimal(10,5)
            - name: foreigners_number
              data_type: int
            - name: foreigners_percentage
              data_type: decimal(10,5)
            - name: national_team_players
              data_type: int
            - name: stadium_name
              data_type: string
            - name: stadium_seats
              data_type: int
            - name: net_transfer_record
              data_type: string
            - name: coach_name
              data_type: double
            - name: last_season
              data_type: int
            - name: filename
              data_type: string
            - name: url
              data_type: string

        - name: raw_competitions
          external:
            location: 's3a://warehouse/bronze/raw_competitions'
          columns:
            - name: competition_id
              data_type: string
            - name: competition_code
              data_type: string
            - name: name
              data_type: string
            - name: sub_type
              data_type: string
            - name: type
              data_type: string
            - name: country_id
              data_type: int
            - name: country_name
              data_type: string
            - name: domestic_league_code
              data_type: string
            - name: confederation
              data_type: string
            - name: url
              data_type: string
            - name: is_major_national_league
              data_type: boolean