bronze:
  outputs:
    dev:
      database: datalake
      host: localhost
      port: 8080
      schema: bronze
      threads: 1
      type: trino
      user: admin
  target: dev


silver:
  outputs:
    dev:
      database: datalake
      host: localhost
      port: 8080
      schema: silver
      threads: 1
      type: trino
      user: admin
  target: dev


gold:
  outputs:
    dev:
      database: datalake
      host: localhost
      port: 8080
      schema: gold
      threads: 1
      type: trino
      user: admin
  target: dev
