bronze:
  outputs:
    dev:
      database: datalake
      host: localhost
      port: 8080
      schema: bronze
      threads: 1
      type: trino
      user: admin
  target: dev


silver:
  outputs:
    dev:
      database: datalake
      host: localhost
      port: 8080
      schema: silver
      threads: 1
      type: trino
      user: admin
  target: dev


gold:
  outputs:
    dev:
      database: datalake
      host: localhost
      port: 8080
      schema: gold
      threads: 1
      type: trino
      user: admin
  target: dev


warehouse:
  outputs:
    dev:
      dremio_space: '@user'
      dremio_space_folder: no_schema
      object_storage_path: '"warehouse_0205"."football"'
      object_storage_source: Data Warehouse
      password: admin123
      port: 9047
      software_host: localhost
      threads: 1
      type: dremio
      use_ssl: false
      user: admin
  target: dev