version: '3.7'

services:
  dremio:
      image: dremio/dremio-oss
      container_name: dremio
      ports:
        - "9047:9047"
        - "31010:31010"
        - "45678:45678"
      volumes:
        - ./data:/opt/dremio/data
      networks:
        - de01-football_leagues_scores_trino-network


networks:
  de01-football_leagues_scores_trino-network:
    external: true